--- # Application configuration - config.yaml
# database:
#         host : 'localhost'
#         user : 'root'
#         passwd : 'Vignesh26'
#         database : 'company'
weekday:

  - monday
  - tuesday
  - wednesday
  - thursday
  - friday
  - saturday
  - sunday
months:

  - jan
  - feb
  - mar
  - apr
  - may
  - june
  - july